import Appbar from "./(views)/components/Appbar";
import Header from "./(views)/components/Header";
import "./scss/main.scss";
import { MantineProvider, createTheme } from "@mantine/core";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  forceColorScheme: "dark",
  fontSizes: {
    xs: 9,
    sm: 11,
    md: 16,
    lg: 24,
    xl: 38,
  },

  colors: {
    "ocean-blue": [
      "#7AD1DD",
      "#5FCCDB",
      "#44CADC",
      "#2AC9DE",
      "#1AC2D9",
      "#11B7CD",
      "#09ADC3",
      "#0E99AC",
      "#128797",
      "#147885",
    ],
    "bright-pink": [
      "#F0BBDD",
      "#ED9BCF",
      "#EC7CC3",
      "#ED5DB8",
      "#F13EAF",
      "#F71FA7",
      "#FF00A1",
      "#E00890",
      "#C50E82",
      "#AD1374",
    ],
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <Header />
          {children}
          <Appbar />
        </MantineProvider>
      </body>
    </html>
  );
}
